# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'churchReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"

  # Pods for churchReact
  pod 'Google/SignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  target 'churchReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  end

  target 'churchReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
